Repository UDM2C/frontlivealone, pull requests merged in 2024-07, with the labels that each got.

#4 Feature/#2 메인 페이지 레이아웃 구성
  src/App.js
  src/components/Main.jsx
  src/pages/MainPage.jsx
  src/pages/MyInfoPage.jsx
  src/styles/Main.module.css
Labels: feat

#8 Feat/#1 PaymentPage, CompletePaymentPage css 구현 완료
  .idea/.gitignore
  .idea/frontlivealone.iml
  .idea/modules.xml
  .idea/vcs.xml
  src/App.js
  src/components/CompletePayment.jsx
  src/components/Payment.jsx
  src/pages/CompletePaymentPage.jsx
  src/pages/PaymentPage.jsx
  src/styles/CompletePaymentPage.module.css
  src/styles/PaymentPage.module.css
Labels: feat

#7 Feature/#5 헤더 레이아웃 구성
  src/assets/logo.png
  src/components/Header.jsx
  src/styles/Header.module.css
Labels: feat

#13 feat:Chatting front구현
  package-lock.json
  package.json
  src/components/chat/ChatBox.jsx
  src/pages/StreamingPage.jsx
  src/styles/Chat.module.css
Labels: feat

#14 Feature/#11 login page
  .gitignore
  .idea/GitCommitMessageStorage.xml
  .idea/material_theme_project_new.xml
  .idea/misc.xml
  package-lock.json
  package.json
  src/App.js
  src/assets/images/google_login.png
  src/assets/images/kakao_login.png
  src/assets/images/login_logo.png
  src/assets/images/naver_login.png
  src/components/Login.jsx
  src/components/Oauth2RedirectHandler.jsx
  src/pages/LoginPage.jsx
Labels: feat

#15 Feature/#10 streamer layout
  package-lock.json
  src/components/BroadcastControl.jsx
  src/components/ChatBox.jsx
  src/components/LiveScreen.jsx
  src/components/ProductionInfo.jsx
  src/components/ProductionInfoInput.jsx
  src/components/Streamer.jsx
  src/pages/StreamerPage.jsx
  src/pages/StreamingPage.jsx
  src/styles/BroadcastControl.module.css
  src/styles/LiveScreen.module.css
  src/styles/ProductionInfo.module.css
  src/styles/ProductionInfoInput.module.css
  src/styles/Streamer.module.css
Labels: feat

#17 Feature/#6 mypage layout
  package-lock.json
  package.json
  src/components/BroadcastHistory.jsx
  src/components/DeliveryHistory.jsx
  src/components/MyInfo.jsx
  src/components/PaymentHistory.jsx
  src/pages/BroadcastHistoryPage.jsx
  src/pages/DeliveryHistoryPage.jsx
  src/pages/MyInfoPage.jsx
  src/pages/PaymentHistoryPage.jsx
  src/styles/History.module.css
  src/styles/MyInfo.module.css
Labels: feat

#20 Feature/#18 token decoding for header
  package-lock.json
  package.json
  src/components/Oauth2RedirectHandler.jsx
  src/index.js
  src/store/store.js
Labels: feat

#21 Feat/#9 chatfront
  src/components/chat/ChatBox.jsx
  src/styles/Chat.module.css
Labels: feat

#23 Feature/#16 header change and JWT Exception
  package-lock.json
  src/App.js
  src/assets/logo.png
  src/axiosInstance.jsx
  src/components/BroadcastControl.jsx
  src/components/Header.jsx
  src/index.js
Labels: feat

#22 Feature/#19 connect myinfo
  src/components/BroadcastHistory.jsx
  src/components/DeliveryHistory.jsx
  src/components/MyInfo.jsx
  src/components/PaymentHistory.jsx
  src/styles/History.module.css
  src/styles/MyInfo.module.css
Labels: feat

#26 Refactor/#25myInfo 페이지 axios -> axiosinstance, 유저 정보 가져와서 보여주기
  package-lock.json
  package.json
  src/components/BroadcastHistory.jsx
  src/components/DeliveryHistory.jsx
  src/components/MyInfo.jsx
  src/components/PaymentHistory.jsx
Labels: feat, fix

#28 Fix/#27 fix anonymous err
  src/store/store.js
Labels: fix

#31 Feature/#24 main and streamer page api
  src/components/BroadcastControl.jsx
  src/components/Header.jsx
  src/components/Main.jsx
  src/components/ProductionInfo.jsx
  src/components/ProductionInfoInput.jsx
  src/components/Streamer.jsx
Labels: feat

#32 Feature/#30 get jwt info
  src/components/Oauth2RedirectHandler.jsx
  src/store/store.js
Labels: feat

#34 Fix/#33 Myinfo 페이지에서 서버로 데이터 전송할 때, header에 token 추가하기
  src/components/BroadcastHistory.jsx
  src/components/DeliveryHistory.jsx
  src/components/MyInfo.jsx
  src/components/PaymentHistory.jsx
Labels: fix

#35 Feat/#9 chatfront
  src/components/chat/ChatBox.jsx
Labels: feat

#37 Fix/#36 streamer monitor css
  src/styles/BroadcastControl.module.css
  src/styles/Streamer.module.css
Labels: fix

#38 Feature/#29 streaming page
  package-lock.json
  package.json
  src/components/HLSPlayer.jsx
  src/components/ProductionInfoForStreaming.jsx
  src/pages/StreamingPage.jsx
  src/styles/StreamingPage.css
Labels: feat

#40 Feature/#39 token reissue
  package-lock.json
  package.json
  src/axiosInstance.jsx
  src/components/Header.jsx
  src/components/Oauth2RedirectHandler.jsx
Labels: feat

#43 Feature/#42 add introduction & advertisement
  src/assets/images/sparta_advertisement.png
  src/components/Main.jsx
  src/components/MyInfo.jsx
  src/styles/Main.module.css
Labels: feat

#45 Feat/#9 chatfront
  package-lock.json
  src/components/chat/ChatBox.jsx
Labels: feat

#46 Feat/#1 카카오페이 구현완료/토스창 붙임 완료
  .env
  package-lock.json
  package.json
  src/App.js
  src/components/Payment.jsx
  src/components/payment/CheckoutPage.jsx
  src/components/payment/FailPage.jsx
  src/components/payment/Payment.jsx
  src/components/payment/SuccessPage.jsx
  src/pages/CheckoutPage.jsx
  src/pages/FailPage.jsx
  src/pages/PaymentPage.jsx
  src/pages/SuccessPage.jsx
Labels: feat

#48 Feature/#47 hls player dispose
  src/components/HLSPlayer.jsx
  src/index.js
Labels: fix

#51 Feature/#50 websocket module
  src/components/chat/ChatBox.jsx
  src/hooks/useWebSocket.jsx
  src/pages/StreamingPage.jsx
  src/pages/WarningPage.jsx
Labels: feat

#52 feat: data.type 세분화, token재 인증 로직 추가
  package-lock.json
  src/components/chat/ChatBox.jsx
  src/hooks/useWebSocket.jsx
Labels: feat
