Repository UDM2C/frontlivealone, pull requests merged in 2024-08, with the labels that each got.

#54 Feat/#1 토스결제 결제위젯->결제창으로 수정 및 디버깅코드 삭제
  .env
  src/App.js
  src/axiosInstance.jsx
  src/components/Login.jsx
  src/components/payment/CheckoutPage.jsx
  src/components/payment/FailPage.jsx
  src/components/payment/Payment.jsx
  src/components/payment/SuccessPage.jsx
  src/pages/CheckoutPage.jsx
  src/pages/FailPage.jsx
  src/pages/StreamingPage.jsx
  src/pages/SuccessPage.jsx
Labels: feat, fix

#56 Feat/#9 chatfront
  src/components/chat/ChatBox.jsx
Labels: fix

#55 Feature/#53 get stream key
  src/assets/images/stream_logo.png
  src/components/ChatBox.jsx
  src/components/Header.jsx
  src/components/LiveScreen.jsx
  src/hooks/useWebSocket.jsx
  src/pages/StreamingPage.jsx
Labels: feat

#60 Fit/#59 Main broadcast title bug
  src/components/Main.jsx
Labels: feat

#61 Feat/#1 스트리머-스트리밍-(구매하기)-결제 연결 중
  src/components/Login.jsx
  src/components/ProductionInfoForStreaming.jsx
  src/components/payment/Payment.jsx
  src/pages/StreamingPage.jsx
Labels: feat, fix

#63 feat: 스트리머-스트리밍-(구매하기)-결제 연결 중
  src/components/payment/Payment.jsx
  src/pages/StreamingPage.jsx
Labels: feat, fix

#65 Fix/#64 aws endpoint fix
  src/axiosInstance.jsx
  src/components/CompletePayment.jsx
  src/components/Login.jsx
  src/components/payment/Payment.jsx
  src/hooks/useWebSocket.jsx
Labels: fix

#66 fix : endpoint 변경
  src/components/LiveScreen.jsx
Labels: fix

#68 Fix/#67 웹소켓 수정 시도
  src/components/LiveScreen.jsx
  src/hooks/useWebSocket.jsx
Labels: fix

#69 Fix/#67 웹소켓 수정 시도한거 원상복귀
  src/components/LiveScreen.jsx
Labels: fix

#71 [Release] Develop -> Release
  src/axiosInstance.jsx
  src/components/CompletePayment.jsx
  src/components/LiveScreen.jsx
  src/components/Login.jsx
  src/components/payment/Payment.jsx
  src/hooks/useWebSocket.jsx
  src/pages/StreamingPage.jsx
Labels: release

#70 Feat/#1 스트리머-스트리밍-(구매하기)-결제 연동
  src/components/Streamer.jsx
  src/components/payment/Payment.jsx
  src/pages/StreamingPage.jsx
Labels: fix

#73 fix: 메시지 버그 수정용 로그
  src/hooks/useWebSocket.jsx
Labels: fix

#74 Feat/#80 release 최신화
  src/components/Streamer.jsx
  src/components/payment/Payment.jsx
  src/pages/StreamingPage.jsx
Labels: fix

#76 Fix/#75 서버 주소 환경변수 설정
  src/axiosInstance.jsx
  src/components/LiveScreen.jsx
  src/components/Login.jsx
  src/components/payment/Payment.jsx
  src/hooks/useWebSocket.jsx
Labels: fix

#78 🩹 fix: REACT_APP_ 환경변수 앞에 붙임
  src/axiosInstance.jsx
  src/components/LiveScreen.jsx
  src/components/Login.jsx
  src/components/payment/Payment.jsx
  src/hooks/useWebSocket.jsx
Labels: fix

#80 Feat/#79 환경변수 가져오는 부분 수정
  src/axiosInstance.jsx
  src/components/LiveScreen.jsx
  src/components/Login.jsx
  src/components/payment/Payment.jsx
  src/hooks/useWebSocket.jsx
Labels: fix

#81 Fix/#77 get info
  src/components/BroadcastControl.jsx
  src/components/Main.jsx
  src/components/ProductionInfoInput.jsx
  src/pages/StreamingPage.jsx
Labels: fix

#82 [Release] develop -> release v2
  src/axiosInstance.jsx
  src/components/BroadcastControl.jsx
  src/components/LiveScreen.jsx
  src/components/Login.jsx
  src/components/Main.jsx
  src/components/ProductionInfoInput.jsx
  src/components/payment/Payment.jsx
  src/hooks/useWebSocket.jsx
  src/pages/StreamingPage.jsx
Labels: release

#84 Fix/#83 Get Product Reduce
  src/components/payment/Payment.jsx
Labels: fix

#85 [Release] develop -> release
  src/components/payment/Payment.jsx
Labels: release

#87 Fix: access token 추가
  src/components/payment/Payment.jsx
Labels: fix

#88 [Release] develop -> release
  src/components/payment/Payment.jsx
Labels: release

#90 Fix/#89 Fix Payment url
  src/components/payment/Payment.jsx
Labels: fix

#91 [Release] develop -> release
  src/components/payment/Payment.jsx
Labels: release

#93 Fix/#92 env gitignore
  .env
  README.md
Labels: fix

#96 ✨ featurer/#95 add admin in myinfoPage
  src/App.js
  src/components/MyInfo.jsx
  src/components/RegisterAdmin.jsx
  src/pages/RegisterAdminPage.jsx
  src/store/store.js
  src/styles/MyInfo.module.css
  src/styles/RegisterAdmin.module.css
Labels: feat

#98 Fix/#94 방송 종료시 프론트 행동 고침
  src/components/BroadcastControl.jsx
  src/components/LiveScreen.jsx
  src/hooks/useWebSocket.jsx
  src/styles/BroadcastControl.module.css
Labels: fix

#100 Feature/#99 order quantity validation
  src/components/Login.jsx
  src/components/payment/Payment.jsx
Labels: feat

#102 Feature/#97 create admin page
  src/App.js
  src/components/Header.jsx
  src/components/MyInfo.jsx
  src/components/RegisterAdmin.jsx
  src/pages/AdminPage.jsx
  src/styles/AdminPage.module.css
  src/styles/MyInfo.module.css
Labels: feat

#104 Feature/#103 broadcast detail page
  src/App.js
  src/components/BroadcastDetail.jsx
  src/pages/AdminPage.jsx
  src/pages/BroadcastDetailPage.jsx
  src/styles/AdminPage.module.css
  src/styles/BroadcastDetail.module.css
Labels: feat

#107 Feature/#106 ten minutes timer
  src/components/Timer.jsx
  src/components/payment/Payment.jsx
  src/pages/StreamingPage.jsx
Labels: feat

#108 Fix/#72 chatting bug
  src/components/chat/ChatBox.jsx
  src/hooks/useWebSocket.jsx
  src/styles/Chat.module.css
Labels: fix

#110 Feat/#101 방송 예약 페이지 개발
  package-lock.json
  package.json
  src/App.js
  src/components/Main.jsx
  src/components/Reservation.jsx
  src/pages/ReservationPage.jsx
  src/styles/Main.module.css
  src/styles/Reservation.module.css
Labels: feat

#111 Feature/#105 get consumer list
  src/App.js
  src/components/ConsumerList.jsx
  src/styles/ConsumerList.module.css
Labels: feat

#113 Feat/#41 찾을 수 없는 페이지
  src/App.js
  src/assets/images/warning.png
  src/components/Main.jsx
  src/pages/WarningPage.jsx
  src/styles/WarningPage.module.css
Labels: feat

#114 fix/#112 admin page details edit
  src/components/ConsumerList.jsx
  src/components/MyInfo.jsx
  src/pages/AdminPage.jsx
  src/pages/BroadcastDetailPage.jsx
  src/styles/AdminPage.module.css
  src/styles/BroadcastDetail.module.css
Labels: fix

#115 Fix/#82 주문내역, 상세페이지 조회 및 페이지네이션 & 결제 취소 시 동작 수정
  .idea/aws.xml
  .idea/checkstyle-idea.xml
  .idea/inspectionProfiles/Project_Default.xml
  src/.idea/src.iml
  src/components/MyInfo.jsx
  src/components/PaymentHistory.jsx
Labels: feat, fix

#117 Feature/#116 road address
  src/components/AddressForm.jsx
  src/components/payment/Payment.jsx
  src/styles/PaymentPage.module.css
Labels: feat

#119 Feat : 결제 페이지에서 상품명과 가격 보여주기
  src/components/payment/Payment.jsx
Labels: feat

#120 Feature/#109 chat servcie
  package-lock.json
  package.json
  src/components/chat/ChatBox.jsx
  src/hooks/useWebSocket.jsx
Labels: feat

#126 test: http -> https
  src/axiosInstance.jsx
  src/components/LiveScreen.jsx
  src/components/Login.jsx
  src/components/payment/Payment.jsx
Labels: test

#128 Refactor/#127 http protocol env
  src/axiosInstance.jsx
  src/components/LiveScreen.jsx
  src/components/Login.jsx
  src/components/payment/Payment.jsx
Labels: refactoring

#133 fix: 채팅창 영어 줄바꿈 수정
  src/hooks/useWebSocket.jsx
  src/styles/Chat.module.css
Labels: fix

#135 Feature/#134 alert product
  src/hooks/useWebSocket.jsx
Labels: feat

#138 Feature/#136 Get Default Address
  src/components/AddressForm.jsx
  src/components/MyInfo.jsx
  src/components/payment/Payment.jsx
  src/styles/MyInfo.module.css
  src/styles/PaymentPage.module.css
Labels: feat

#139 Fix /#137 방송 시작, 방송 종료 반영
  src/components/BroadcastControl.jsx
  src/components/LiveScreen.jsx
  src/components/Streamer.jsx
  src/hooks/useWebSocket.jsx
Labels: fix

#141 Refactor/#140 웹소켓 한 번만 실행되도록 리팩토링
  src/components/LiveScreen.jsx
  src/components/Streamer.jsx
  src/components/chat/ChatBox.jsx
  src/pages/StreamingPage.jsx
Labels: refactoring

#142 Feat/#131 스트림랩 가이드 페이지 추가
  .github/workflows/main.yml
  src/.idea/.gitignore
  src/.idea/aws.xml
  src/.idea/checkstyle-idea.xml
  src/.idea/misc.xml
  src/.idea/modules.xml
  src/.idea/vcs.xml
  src/App.js
  src/assets/images/streamlab1.png
  src/assets/images/streamlab10.png
  src/assets/images/streamlab2.png
  src/assets/images/streamlab3.png
  src/assets/images/streamlab4.png
  src/assets/images/streamlab5.png
  src/assets/images/streamlab6.png
  src/assets/images/streamlab7.png
  src/assets/images/streamlab8.png
  src/assets/images/streamlab9.png
  src/axiosInstance.jsx
  src/components/Main.jsx
  src/pages/GuidePage.jsx
  src/styles/GuidePage.module.css
  src/styles/Main.module.css
Labels: feat

#143 feat: 시청자 수 표시 추가
  src/components/Streamer.jsx
  src/hooks/useWebSocket.jsx
Labels: feat

#144 feat : bytes수 제한 , Main.jsx줄바꿈 (protocol설정)
  src/components/Main.jsx
  src/components/chat/ChatBox.jsx
Labels: feat

#147 Fix/#145 use effect에서 stream key 요청하는 것 없애고 소켓 세션 열릴 때로 옮김
  src/axiosInstance.jsx
  src/components/LiveScreen.jsx
  src/hooks/useWebSocket.jsx
Labels: fix

#148 Style/#146 AdminPage css edit
  src/pages/AdminPage.jsx
  src/styles/AdminPage.module.css
Labels: refactoring

#151 Refactor/#149 broadcast details page css
  src/components/BroadcastDetail.jsx
  src/styles/BroadcastDetail.module.css
Labels: refactoring

#154 Refactor/#152 live screen css refactor
  src/assets/images/live_icon.png
  src/components/Main.jsx
  src/components/ProductionInfoForStreaming.jsx
  src/pages/StreamingPage.jsx
  src/store/store.js
  src/styles/StreamingPage.css
Labels: refactoring

#155 Refactor/#153 admin user list css
  src/styles/ConsumerList.module.css
Labels: refactoring

#157 Refactor/#156 Adming register page css
  src/components/RegisterAdmin.jsx
  src/styles/RegisterAdmin.module.css
Labels: refactoring

#158 Feature/#109 chat servcie
  src/components/chat/ChatBox.jsx
Labels: refactoring

#161 Style/#159 스트리머 페이지 css 수정
  src/components/BroadcastControl.jsx
  src/components/LiveScreen.jsx
  src/components/ProductionInfo.jsx
  src/components/ProductionInfoInput.jsx
  src/components/Streamer.jsx
  src/components/StreamerScreen.jsx
  src/styles/BroadcastControl.module.css
  src/styles/LiveScreen.module.css
  src/styles/ProductionInfo.module.css
  src/styles/ProductionInfoInput.module.css
  src/styles/Streamer.module.css
  src/styles/StreamerScreen.module.css
Labels: refactoring

#163 Refactor/#162 login page css refactor
  src/assets/images/login_background.png
  src/components/Login.jsx
  src/styles/Login.css
Labels: refactoring

#165 Refactor/#160 mypage css
  src/components/MyInfo.jsx
  src/styles/MyInfo.module.css
Labels: refactoring

#166 feat: 채팅창 유저 색깔 표시
  src/components/chat/ChatBox.jsx
  src/hooks/useWebSocket.jsx
  src/styles/Chat.module.css
Labels: feat

#171 Refactor/#170 Guide page css
  src/pages/GuidePage.jsx
  src/styles/GuidePage.module.css
Labels: refactoring

#173 fix : 호버링 시 margin이 변경되지 않도록 수정
  src/styles/Chat.module.css
Labels: fix

#174 Fix /#131 디폴트 방송상태 수정
  src/components/Main.jsx
  src/styles/Main.module.css
Labels: fix

#177 Refactor/#176 streaming page css refactor
  src/styles/StreamingPage.css
Labels: refactoring

#180 fix:채팅 UI 변경
  src/styles/Chat.module.css
Labels: fix

#181 Refactor/#179 마진 없애기
  src/components/LiveScreen.jsx
  src/components/StreamerScreen.jsx
  src/styles/LiveScreen.module.css
  src/styles/StreamerScreen.module.css
Labels: refactoring

#182 refactor: 채팅창 크기 조정
  src/components/chat/ChatBox.jsx
  src/pages/StreamingPage.jsx
  src/styles/Chat.module.css
Labels: refactoring

#183 Fix /#131 디폴트 방송상태 수정 + 스트리밍 화면 컨테이너 수정 + 푸터 추가
  src/App.js
  src/components/Footer.jsx
  src/components/Main.jsx
  src/styles/CompletePaymentPage.module.css
  src/styles/Footer.module.css
  src/styles/History.module.css
  src/styles/Main.module.css
  src/styles/StreamingPage.css
Labels: fix, refactoring

#185 Fix/#184 broadcast title bug fix
  src/pages/StreamingPage.jsx
Labels: fix

#186 Fix/#175 myinfo page get err
  src/App.js
  src/components/BroadcastHistory.jsx
  src/components/DeliveryHistory.jsx
  src/components/MyInfo.jsx
  src/components/RegisterAdmin.jsx
  src/pages/AdminPage.jsx
  src/styles/AdminPage.module.css
  src/styles/BroadcastDetail.module.css
  src/styles/History.module.css
  src/styles/MyInfo.module.css
Labels: fix

#188 Refactor/#187 Get total sale price
  src/components/BroadcastHistory.jsx
  src/components/MyInfo.jsx
  src/styles/History.module.css
Labels: refactoring

#189 Fix /#131-푸터 링크 수정 및 사이트 이름, 로고 수정
  public/favicon.ico
  public/index.html
  public/logo512.png
  src/components/Footer.jsx
Labels: fix, refactoring

#190 feat:시청자 수 표시 방법 변경 -> 새로운 세션이 들어올 때마다
  src/hooks/useWebSocket.jsx
Labels: feat

#191 feat: 주석처리된 메서드 삭제
  src/hooks/useWebSocket.jsx
Labels: fix

#194 Feature/#109 chat servcie
  src/hooks/useWebSocket.jsx
Labels: feat

#193 Docs/#192 create readme
  README.md
Labels: documentation

#195 fix:메인페이지로 돌아가기 일단 하드코딩으로 바꾸기
  src/components/CompletePayment.jsx
Labels: fix

#197 fix : 비디오 모서리 둥글게 해제
  src/styles/StreamingPage.css
Labels: refactoring

#198 Feature/#109 chat servcie
  src/hooks/useWebSocket.jsx
  src/pages/StreamingPage.jsx
Labels: feat

#200 Fix/#199 streaming page enter way
  src/components/Main.jsx
Labels: fix

#202 Fix/#201 deactivation buying product for default broadcast
  src/pages/StreamingPage.jsx
Labels: fix

#205 fix : 로그아웃 후 메인페이지로 이동하도록 수정
  src/components/Header.jsx
Labels: fix

#206 Fix: 페이지 고정 시키기
  src/components/PaymentHistory.jsx
  src/styles/History.module.css
Labels: fix

#208 Docs/#207 update readme
  README.md
Labels: documentation

#210 fix : 로딩 문구 변경
  src/pages/StreamingPage.jsx
Labels: fix

#212 Fix/#131 주문내역 페이지네이션 동적으로 변경
  src/components/PaymentHistory.jsx
Labels: fix

#213 Fix/#211 get history page edit
  src/components/BroadcastHistory.jsx
  src/components/DeliveryHistory.jsx
  src/components/MyInfo.jsx
  src/pages/AdminPage.jsx
  src/styles/History.module.css
Labels: fix

#214 Fix /#82 주문내역 페이지네이션 버그수정
  src/components/MyInfo.jsx
  src/components/PaymentHistory.jsx
Labels: fix

#215 Fix/#82 주문내역 버그수정완료
  src/App.js
  src/components/MyInfo.jsx
  src/components/PaymentHistory.jsx
  src/pages/PaymentHistoryPage.jsx
Labels: fix

#217 🩹 fix: get payment err
  src/components/MyInfo.jsx
Labels: fix
